apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bylchagzn-python 
  janus-idp.io/tekton: bylchagzn-python
  backstage.io/kubernetes-id: bylchagzn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bylchagzn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml